--1. Obtener todas las mascotas activas
--Solo muestra: nombre, peso
SELECT NAME, WEIGHT FROM PETS WHERE IS_ACTIVE = TRUE;

--2. Listar todas las citas futuras
-- Ordenadas por fecha ascendente
SELECT * FROM APPOINTMENTS;

SELECT *
FROM APPOINTMENTS
WHERE
    START_TIME > NOW()
ORDER BY START_TIME ASC;

--3. Obtener todos los dueños con
-- su número de teléfono
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS OWNERS,
    PHONE_NUMBER
FROM OWNERS
    JOIN PERSONAL_DATA ON OWNERS.PERSONAL_DATA_ID = PERSONAL_DATA.ID;

--4. Mostrar todas las mascotas con su dueño
-- nombre mascota
-- nombre dueño
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS OWNER,
    NAME AS PET
FROM
    OWNERS_PETS
    JOIN OWNERS ON OWNERS_PETS.OWNER_ID = OWNERS.ID
    JOIN PETS ON OWNERS_PETS.PET_ID = PETS.ID
    JOIN PERSONAL_DATA ON OWNERS.PERSONAL_DATA_ID = PERSONAL_DATA.ID;

-- 5. Mostrar todas las citas con: mascota, dueño
-- veterinario y fecha
SELECT * FROM APPOINTMENTS;

SELECT
    PERSONAL_DATA.FIRST_NAME || ' ' || PERSONAL_DATA.LAST_NAME AS OWNERS,
    PERSONAL_DATA_2.FIRST_NAME || ' ' || PERSONAL_DATA_2.LAST_NAME AS VET,
    NAME AS PET,
    APPOINTMENTS.CREATED_AT
FROM
    APPOINTMENTS
    JOIN OWNERS_PETS ON OWNERS_PETS.ID = APPOINTMENTS.OWNER_PET_ID
    JOIN PETS ON OWNERS_PETS.PET_ID = PETS.ID
    JOIN OWNERS ON OWNERS_PETS.OWNER_ID = OWNERS.ID
    JOIN PERSONAL_DATA ON OWNERS.PERSONAL_DATA_ID = PERSONAL_DATA.ID
    JOIN STAFF ON APPOINTMENTS.STAFF_ID = STAFF.ID
    JOIN PERSONAL_DATA PERSONAL_DATA_2 ON STAFF.PERSONAL_DATA_ID = PERSONAL_DATA_2.ID;