-- Exercises to practice

--1. Obtener todas las mascotas activas
--Solo muestra: nombre, peso
SELECT NAME, WEIGHT FROM PETS WHERE IS_ACTIVE = TRUE;

--2. Listar todas las citas futuras
-- Ordenadas por fecha ascendente
SELECT * FROM APPOINTMENTS;

SELECT *
FROM APPOINTMENTS
WHERE
    START_TIME > NOW()
ORDER BY START_TIME ASC;

--3. Obtener todos los dueños con
-- su número de teléfono
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS OWNERS,
    PHONE_NUMBER
FROM OWNERS
    JOIN PERSONAL_DATA ON OWNERS.PERSONAL_DATA_ID = PERSONAL_DATA.ID;

--4. Mostrar todas las mascotas con su dueño
-- nombre mascota
-- nombre dueño
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS OWNER,
    NAME AS PET
FROM
    OWNERS_PETS
    JOIN OWNERS ON OWNERS_PETS.OWNER_ID = OWNERS.ID
    JOIN PETS ON OWNERS_PETS.PET_ID = PETS.ID
    JOIN PERSONAL_DATA ON OWNERS.PERSONAL_DATA_ID = PERSONAL_DATA.ID;

-- 5. Mostrar todas las citas con: mascota, dueño
-- veterinario y fecha

SELECT * FROM APPOINTMENTS;

SELECT
    PERSONAL_DATA.FIRST_NAME || ' ' || PERSONAL_DATA.LAST_NAME AS OWNERS,
    PERSONAL_DATA_2.FIRST_NAME || ' ' || PERSONAL_DATA_2.LAST_NAME AS VET,
    NAME AS PET,
    APPOINTMENTS.CREATED_AT
FROM
    APPOINTMENTS
    JOIN OWNERS_PETS ON OWNERS_PETS.ID = APPOINTMENTS.OWNER_PET_ID
    JOIN PETS ON OWNERS_PETS.PET_ID = PETS.ID
    JOIN OWNERS ON OWNERS_PETS.OWNER_ID = OWNERS.ID
    JOIN PERSONAL_DATA ON OWNERS.PERSONAL_DATA_ID = PERSONAL_DATA.ID
    JOIN STAFF ON APPOINTMENTS.STAFF_ID = STAFF.ID
    JOIN PERSONAL_DATA PERSONAL_DATA_2 ON STAFF.PERSONAL_DATA_ID = PERSONAL_DATA_2.ID;

--6.Obtener todas las citas 'Pending'
-- Mostrar: id cita, mascota y fecha

SELECT APPOINTMENTS.ID, APPOINTMENTS.START_TIME AS "date", PETS.NAME AS PET
FROM
    APPOINTMENTS
    JOIN OWNERS_PETS ON APPOINTMENTS.OWNER_PET_ID = OWNERS_PETS.ID
    JOIN PETS ON PETS.ID = OWNERS_PETS.PET_ID
    JOIN APPOINTMENT_STATUS AST ON APPOINTMENT_STATUS.ID = APPOINTMENTS.APPOINTMENT_STATUS_ID
WHERE
    AST.NAME = 'Pending';

-- short mode

SELECT A.ID, A.START_TIME AS "date", P.NAME AS PET, AST.NAME
FROM
    APPOINTMENTS A
    JOIN OWNERS_PETS OP ON A.OWNER_PET_ID = OP.ID
    JOIN PETS P ON P.ID = OP.PET_ID
    JOIN APPOINTMENT_STATUS AST ON AST.ID = A.APPOINTMENT_STATUS_ID

--7. Mascotas por cada dueño, mostrar dueño y cantidad de mascota

SELECT PD.FIRST_NAME || ' ' || PD.LAST_NAME AS OWNER, COUNT(OP.PET_ID) AS PET_NUMBER
FROM
    OWNERS_PETS OP
    JOIN OWNERS O ON O.ID = OP.OWNER_ID
    JOIN PERSONAL_DATA PD ON PD.ID = O.PERSONAL_DATA_ID
GROUP BY (PD.FIRST_NAME, PD.LAST_NAME);

-- 8. Contar cuántas citas ha atendido cada veterinario
-- nombre veterinario y total de citas

SELECT PD.FIRST_NAME || ' ' || PD.LAST_NAME AS VET, COUNT(A.ID) AS TOTAL_APPOINTMENTS
FROM
    APPOINTMENTS A
    JOIN STAFF S ON S.ID = A.STAFF_ID
    JOIN PERSONAL_DATA PD ON PD.ID = S.PERSONAL_DATA_ID
    JOIN APPOINTMENT_STATUS AST ON AST.ID = A.APPOINTMENT_STATUS_ID
WHERE
    AST.NAME = 'Completed'
GROUP BY (PD.FIRST_NAME, PD.LAST_NAME);

-- 9. Obtener las especies con más mascotas
-- especie, cantidad

SELECT B.NAME, COUNT(P.NAME) AS TOTAL
FROM PETS P
    JOIN BREEDS B ON B.ID = P.BREED_ID
GROUP BY (B.ID)
ORDER BY TOTAL DESC;



-- 10. Obtener las próximas citas de un veterinario 
-- específico
-- solo citas futuras y por fecha
SELECT
	SE.NAME AS SERVICE_NAME,
	PD.FIRST_NAME || ' ' || PD.LAST_NAME AS VET,
	A.START_TIME AS APPOINTMENTS_SOON
FROM
	APPOINTMENTS A
	JOIN STAFF S ON S.ID = A.STAFF_ID
	JOIN PERSONAL_DATA PD ON PD.ID = S.PERSONAL_DATA_ID
	JOIN SERVICES SE ON SE.ID = A.SERVICE_ID
WHERE
	A.START_TIME > NOW();
